version: '3.9'

services:
    postgres:
        image: postgres
        container_name: ${DB_HOST}
        restart: on-failure
        environment: 
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data 

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: on-failure
        command: sh -c "python3 manage.py makemigrations && 
                        python3 manage.py migrate --no-input && 
                        python3 manage.py collectstatic --no-input && 
                        uwsgi --ini uwsgi.ini"
        #gunicorn -k gevent config.wsgi:application -b 0.0.0.0:8000"
        depends_on: 
            - postgres
        expose: 
            - "8000"
        networks:
            - main
        volumes: 
            - .:/code/
            - ./static:/app/static
            - ./media:/app/media
        
    nginx:
        image: nginx
        container_name: nginx
        command: nginx -g 'daemon off;'
        restart: on-failure
        depends_on:
            - app
        networks: 
            - main
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./data/nginx/conf.d:/etc/nginx/conf.d
            - ./media:/app/media
            - ./static:/app/static
            - ./data/certbot/conf:/etc/nginx/ssl/:ro
            - ./data/certbot/www:/var/www/certbot/:ro

    certbot:
      image: certbot/certbot
      container_name: certbot
      restart: unless-stopped
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt/:rw
        - ./data/certbot/www:/var/www/certbot/:rw
      #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



networks:
  main:

volumes:
  static:

  media:

  postgres_data: